meta_product_name: "Arbitre d'escrime"
meta_title: "Arbitre d'escrime - S'entraîner aux qcms"
meta_description: "Entraînes-toi aux qcms d'arbitre départemental ou régional d'escrime!"
meta_image: "banner_resized.jpg" # should exist in `app/assets/images/`
